# -*- encoding: utf-8 -*-
"""
KERI
keri.base.keeping module


"""


from .. import kering
from ..db import dbing


def openKeep(name="test", **kwa):
    """
    Returns contextmanager generated by openLMDB but with Keeper instance
    """
    return dbing.openLMDB(cls=Keeper, name=name, **kwa)


class Keeper(dbing.LMDBer):
    """
    Keeper sets up named sub databases for key pair storage.  Methods provide
    key pair creation and data signing.

    Attributes:
        see superclass LMDBer for inherited attributes

        .prms is named sub DB whose values are parameters for keeper
            dgKey
            DB is keyed by identifer prefix plus digest of serialized event
            Only one value per DB key is allowed

        .keys is named sub DB whose values are private keys
            dgKey
            DB is keyed by identifer prefix plus dig

        .dtss is named sub DB of datetime stamp strings in ISO 8601 format of
            dgKey
            the datetime when the event was first seen by log.
            Used for escrows timeouts and extended validation.
            DB is keyed by identifer prefix plus digest of serialized event

    Properties:


    """
    HeadDirPath = "/usr/local/var"  # default in /usr/local/var
    TailDirPath = "keri/keep"
    AltHeadDirPath = "~"  #  put in ~ as fallback when desired not permitted
    AltTailDirPath = ".keri/keep"
    TempHeadDir = "/tmp"
    TempPrefix = "keri_keep_"
    TempSuffix = "_test"
    MaxNamedDBs = 8

    def __init__(self, headDirPath=None, reopen=True, **kwa):
        """
        Setup named sub databases.

        Inherited Parameters:
            name is str directory path name differentiator for main database
                When system employs more than one keri database, name allows
                differentiating each instance by name
            temp is boolean, assign to .temp
                True then open in temporary directory, clear on close
                Othewise then open persistent directory, do not clear on close
            headDirPath is optional str head directory pathname for main database
                If not provided use default .HeadDirpath
            reopen is boolean, IF True then database will be reopened by this init

        Notes:

        dupsort=True for sub DB means allow unique (key,pair) duplicates at a key.
        Duplicate means that is more than one value at a key but not a redundant
        copies a (key,value) pair per key. In other words the pair (key,value)
        must be unique both key and value in combination.
        Attempting to put the same (key,value) pair a second time does
        not add another copy.

        Duplicates are inserted in lexocographic order by value, insertion order.

        """
        super(Keeper, self).__init__(headDirPath=headDirPath, reopen=reopen, **kwa)

        if reopen:
            self.reopen(headDirPath=headDirPath)


    def reopen(self, temp=None, headDirPath=None):
        """
        Open sub databases
        """
        super(Keeper, self).reopen(temp=temp, headDirPath=headDirPath)

        # Create by opening first time named sub DBs within main DB instance
        # Names end with "." as sub DB name must include a non Base64 character
        # to avoid namespace collisions with Base64 identifier prefixes.

        self.prms = self.env.open_db(key=b'prms.')
        self.keys = self.env.open_db(key=b'keys.')
        self.dtss = self.env.open_db(key=b'dtss.')

