# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.com/platform/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  apt_packages:
    - libsodium-dev
  tools:
    python: "3.13"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
   builder: dirhtml

# Install keripy itself (for import keri in conf.py) then Sphinx dependencies
python:
   install:
   - method: pip
     path: .
   - requirements: docs/requirements.txt
